#!/usr/bin/env bash
set -euo pipefail

die() {
    printf 'error: %s\n' "$*" >&2
    exit 1
}

worktree_dir="${1:-$PWD}"
[[ -d "$worktree_dir" ]] || die "worktree directory does not exist: $worktree_dir"
worktree_dir="$(cd "$worktree_dir" && pwd -P)"

search_dir="$worktree_dir"
container_root=""

while [[ "$search_dir" != "/" ]]; do
    if [[ -d "$search_dir/.bare" ]]; then
        container_root="$search_dir"
        break
    fi
    search_dir="$(dirname "$search_dir")"
done

if [[ -z "$container_root" ]]; then
    container_root="$worktree_dir"
fi

command -v opencode >/dev/null || die "opencode is not on PATH"

worktree_name="$(basename "$worktree_dir")"
context_dir="$container_root/.opencode-zellij-contexts"
context_file="$context_dir/$worktree_name.md"
mkdir -p "$context_dir"

if git -C "$worktree_dir" rev-parse --is-inside-work-tree >/dev/null 2>&1; then
    worktree_ref="$(git -C "$worktree_dir" symbolic-ref --quiet --short HEAD 2>/dev/null || git -C "$worktree_dir" rev-parse --short HEAD)"
else
    worktree_ref="not a git worktree"
fi

{
    printf '# Zellij Worktree Context\n\n'
    printf 'This file is generated by `%s` when the zellij worktree opencode pane starts.\n\n' "$0"
    printf '%s\n' "- Opencode session root: \`$worktree_dir\`"
    printf '%s\n' "- Mono container root: \`$container_root\`"
    printf '%s\n' "- Active zellij worktree: \`$worktree_dir\`"
    printf '%s\n\n' "- Active worktree ref at launch: \`$worktree_ref\`"
    printf 'Use the active zellij worktree for repo code edits, package commands, git status/diff, and tests unless the user explicitly asks for another worktree or mono-root tooling.\n'
    printf 'Before editing repo code, read the active worktree `AGENTS.md`; worktree-local instructions override mono-root notes for repo work.\n'
} > "$context_file"

export OPENCODE_CONFIG_CONTENT="{\"instructions\":[\"AGENTS.md\",\"$context_file\"]}"

env_file="${OPENCODE_WEB_ENV_FILE:-$HOME/.local/state/opencode-web.env}"
if [[ -f "$env_file" ]]; then
    set -a
    # shellcheck disable=SC1090
    source "$env_file"
    set +a
fi

web_port="${OPENCODE_WEB_PORT:-4096}"
web_host="${OPENCODE_WEB_HOST:-127.0.0.1}"
web_url="${OPENCODE_WEB_URL:-http://$web_host:$web_port}"
attach_args=(attach "$web_url" --dir "$worktree_dir")
[[ -n "${OPENCODE_SERVER_USERNAME:-}" ]] && attach_args+=(--username "$OPENCODE_SERVER_USERNAME")
[[ -n "${OPENCODE_SERVER_PASSWORD:-}" ]] && attach_args+=(--password "$OPENCODE_SERVER_PASSWORD")

if [[ "${PROXIMAL_OPENCODE_DRY_RUN:-0}" == "1" ]]; then
    printf 'cwd=%s\n' "$worktree_dir"
    printf 'container_root=%s\n' "$container_root"
    printf 'worktree=%s\n' "$worktree_dir"
    printf 'context=%s\n' "$context_file"
    printf 'config_content=%s\n' "$OPENCODE_CONFIG_CONTENT"
    redacted_attach_args=("${attach_args[@]}")
    for i in "${!redacted_attach_args[@]}"; do
        if [[ "${redacted_attach_args[$i]}" == "--password" && $((i + 1)) -lt ${#redacted_attach_args[@]} ]]; then
            redacted_attach_args[$((i + 1))]="<redacted>"
        fi
    done
    printf 'attach=%q' opencode
    printf ' %q' "${redacted_attach_args[@]}"
    printf '\n'
    exit 0
fi

exec opencode "${attach_args[@]}"
